### ISSUE TITLE
Implement intrinsicContentSize

### ISSUE THREAD

**Issue by phix23** [mownier/MONActivityIndicatorView#5]
Please implement this method as follows and call `invalidateIntrinsicContentSize` instead of `adjustFrame`. This way it plays well together with iOS auto-layout.

```
-(CGSize)intrinsicContentSize
{
    return CGSizeMake((self.numberOfCircles * ((2 * self.radius) + self.internalSpacing)) - self.internalSpacing, self.radius * 2);
}
```

The issue I'm having is that I can't center the view horizontally using layout constraints without knowing the exact width of the view. With `intrinsicContentSize` implemented, it would layout automatically.

**Comment by mownier** [comment]
Hi @phix23, I already did the implementation of `intrinsicContentSize` method and used the `invalidateIntrinsicContentSize`. Thanks. Cheers!
